swagger: '2.0'
info: 
  title: Subsum api documentation
  description: Api documentation for subsum each request comes with a cookie sent from the client
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    -url: 'http://apache.org/'
  servers:
    -url: https://subsum-server.onrender.com
    description: subsum website link
schemes: [http, https]

paths:
  /:
    get:
      summary: Home get request
      description: the first request to check server
      responses:
        200:
          description: Success
  /api/web/auth/login:
    post:
      summary: Login user
      description: login a user Required Fields- *emailOrMobile, *password
      responses:
        401:
          description: All inputs feilds are required email and password
        403: 
          description: Wrong password or email address
        500: 
          description: Server Error
        200: 
          description: signup successfull but account not verified
        201:
          description: signup successfull and cookie set to server url
          schema:
            type: object
            properties:
              _id:
                type: string
              username: 
                type: string
              firstName:
                type: string
              lastName:
                type: string
              mobile:
                type: string
              profile:
                type: string
              acctBalance:
                type: number
              transactionTotal:
                type: number
              refCode:
                type: string
              referralLink:
                type: string
              referrals:
                type: array
              referredBy:
                type: string
              verified:
                type: boolean
              blocked:
                type: boolean
  /api/web/auth/forgotPassword:       
    post:
      summary: Forgot password
      description: forgot password for a user with user email required feilds *email
      responses:
        404:
          description: Email address does not exist
        500:
          description: Internal server error
        200:
          description: Reset email sent
  /api/web/auth/resetPassword/:resetToken:       
    post:
      summary: Reset password
      description: Reset Password endpoint for user Required body *password, *confirmPassword
      responses:
        400:
          description: User error
          schema:
            type: string
            example:
              1. Passwords must be at least 6 characters 2. password do not match 3. Passwords must contain at least one special character 4. Invalid Reset Token    
        500:
          description: Internal server error
        201:
          description: Password Reset success
  /api/web/user/updateUser:       
    post:
      summary: Update user body data- username, firstName, lastName, email, mobile
      description: Update user info endpoint
      responses:
        404:
          description: No user with this id found
        500:
          description: Internal server error
        200:
          description: Update successful
  /api/web/user/getAllUserReferrees:       
    get:
      summary: User referrals
      description: Get all people referred by user 
      responses:
        500:
          description: Internal server error
        200:
          description: successful
          schema:
            type: array
            items:
              type: object
  /api/web/transaction/fetchAllUserTractions:       
    get:
      summary: Fetch all transaction of a user
      description: Get all transaction done by user
      responses:
        500:
          description: Internal server error
        200:
          description: successful transaction data sent
  /api/web/transaction/fetchAUserTraction/:id:       
    get:
      summary: Fetch a transaction of a user
      description: Get a transaction done by user
      responses:
        500:
          description: Internal server error
        403: 
          description: Invalid user
        200:
          description: successful transaction data sent to the client
  /api/web/airtimeToCash/convertAirtimeToCash:       
    post:
      summary: Endpoint of user to convert airtime to cash
      description: required body- networkCode, phoneNumber, amount, airtimeSharePin
      responses:
        500:
          description: Internal server error
        403: 
          description: Invalid user
        200:
          description: successful transaction data sent to the client

